project/proj/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


from proj import settings
from ques import views
from company import views as vc
from profiles import views as vp
from wiki import views as vw
from buh import views as vb

urlpatterns = patterns('',

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^admin_tools/', include('admin_tools.urls')),

    url(r'^tinymce/', include('tinymce.urls')),


    #working
    url(r'^$',                          views.IndexView.as_view(), name='main'),
    url(r'^add_q/$',                    views.QuesAdd.as_view(), name=u'add_q'),
    url(r'^chat/(?P<pk>\d+)/$',         views.QuesChatForm.as_view(), name = u'chat'),
    url(r'^pc_list/$',                  vc.PcList.as_view(), name = 'pc_list'),
    url(r'^pc_detail/(?P<pk>\d+)/$',    vc.PcDetail.as_view(), name='pc_detail'),
    url(r'^pc_history/(?P<pk>\d+)/$',   vc.PcOptionHistoryView.as_view()),
    url(r'^change_opt/(?P<pk>\d+)/$',   vc.ChangePcOption.as_view(), name='option_change'),
    url(r'^add_opt/(?P<pk>\d+)/$',      vc.AddPcOption.as_view(), name='add_option' ),
    url(r'^add_pc/$',                   vc.AddCompanyPcView.as_view(), name='add_pc'),
    url(r'^add_pc_option_for_all/(?P<pk>\d+)/$',    vc.AddPcOptionForAllView.as_view(), name='add_pc_option_for_all'),
    url(r'^report_ques/$',              views.MainReportForQuestionsView.as_view(), name='report_ques'),
    url(r'^report_pc_history/$',        views.MainReportForPcHistoryView.as_view(), name='report_pc_history'),
    url(r'^short_company_name/$',       vc.ShortCompanyNameListView.as_view(), name='short_company_name'),
    url(r'^add_dep/$',                  vc.AddDepartamentView.as_view(), name='add_dep'),
    url(r'^add_file_for_pc/(?P<pk>\d+)/$', vc.AddFileForPcView.as_view(), name='file_for_pc'),
    url(r'^add_user/$',                 vp.CreateUserView.as_view(), name='add_user'),
    url(r'^user_list/$',                vp.UserListView.as_view(), name='user_list'),
    url(r'^company_list/$',             vp.CompanyListView.as_view(), name='company_list'),
    url(r'^add_company/$',              vp.CreateCompanyView.as_view(), name='add_company'),
    url(r'^add_companyadmins_for_user/(?P<pk>\d+)/$', vp.AddCompanyAdminsForUserView.as_view(), name='add_copmanyadmins_for_user'),
    url(r'^companyadmins_for_user/(?P<pk>\d+)/$', vp.CompanyAdminsForUserListView.as_view(), name='companyadmins_for_user'),
    url(r'^companyadmins_for_company/(?P<pk>\d+)/$', vp.CompanyAdminsForCompanyListView.as_view(), name='companyadmins_for_company'),
    url(r'^add_companyadmins_for_company/(?P<pk>\d+)/$', vp.AddCompanyAdminsForCompanyView.as_view(), name='add_companyadmins_for_company'),
    url(r'^chnage_user_to_for_ques/(?P<pk>\d+)/$',    views.ChangeUserToForQuestionView.as_view(), name='change_user_to_for_ques'),
    url(r'^departament_list/$',         vc.DepartamentsListView.as_view(), name='dep_list'),
    url(r'^edit_dep/(?P<pk>\d+)/$',     vc.EditDepartamentView.as_view(), name='edit_dep'),
    url(r'^edit_question/(?P<pk>\d+)/$', views.EditQuesView.as_view(), name='edit_question'),
    url(r'^add_post/$',                 vc.AddPostView.as_view(), name='add_post'),
    url(r'^posts_list/$',               vc.PostsListView.as_view(), name='posts_list'),
    url(r'^edit_post/(?P<pk>\d+)/$',    vc.PostEditView.as_view(), name='edit_post'),
    url(r'^edit_user/(?P<pk>\d+)/$',    vp.EditUserView.as_view(), name='edit_user'),
    url(r'^buh_index/$',                vb.IndexAccountingView.as_view(), name='buh_index'),
    url(r'^add_accounting/$',           vb.AddAccountingView.as_view(), name='add_accounting'),
    url(r'^add_contract/$',             vb.AddContractView.as_view(), name='add_contract'),
    url(r'^contracts_list/$',           vb.ListContractsView.as_view(), name='list_contracts'),
    url(r'^edit_contract/(?P<pk>\d+)/$', vb.EditContractView.as_view(), name='edit_contract'),


    #### WIKI ####
    url(r'^wiki/$',                     vw.IndexWikiView.as_view(), name='wiki'),
    url(r'^add_page_wiki/$',            vw.AddArticleView.as_view(), name='add_page_wiki'),
    url(r'^read_page_wiki/(?P<pk>\d+)/$', vw.ReadArcticleView.as_view(), name='read_page_wiki'),
    url(r'^edit_page_wiki/(?P<pk>\d+)/$', vw.EditArticleView.as_view(), name='edit_page_wiki'),


    #### End WIKI ####


    #tehnikal
    url( r'^accounts/login/$',  'profiles.views.login'),
    url( r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login', {'login_url': '/accounts/login/'} ),


    #ajax views
    url(r'^ajax/get_pc_from/$',                                     vc.GetPcFrom.as_view()),
    url(r'^ajax/get_ques/(?P<pk>\d+)/$',                            views.GetQuestionForChat.as_view()),
    url(r'^ajax/get_chat_mess/(?P<pk>\d+)/$',                       views.GetChatMessages.as_view()),
#    url(r'^ajax/get_index_ques/$',                                  views.QuestionList.as_view()),
    url(r'^ajax/get_company_for_pc_list/$',                         vc.GetCompanyForPcList.as_view(), name='ajax_GetCompanyForPcList'),
    url(r'^ajax/get_pc_for_list/(?P<company>\d+)/(?P<dep>\d+)/$',   vc.GetPcForPcList.as_view()),
    url(r'^ajax/get_options_for_add/(?P<pk>\d+)/$',                 vc.GetOptionsForAdd.as_view()),
    url(r'^ajax/get_company_for_pc_add/$',                          vc.GetCompanyForPcAddView.as_view()),
    url(r'^ajax/get_company_for_report_ques/$',                     views.GetCompanyListForReportForQuesView.as_view()),
    url(r'^ajax/get_users_for_report_ques/$',                       views.GetUserListForReportForQuesView.as_view()),
    url(r'^ajax/get_report_for_report_ques/(?P<company>\d+)/(?P<user>\d+)/$', views.GetReportListForReportForQuesView.as_view()),
    url(r'^ajax/get_pc_for_report_pc_history/(?P<company>\d+)/$',   views.GetPcListForReportPcHistoryView.as_view()),
    url(r'^ajax/get_company_for_report_pc_history/$',               views.GetCompanyListForReportForPcHistoryView.as_view()),
    url(r'^ajax/get_report_pc_history/(?P<pc>\d+)/(?P<user>\d+)/(?P<company>\d+)/$', views.GetReportForPcHistoryView.as_view()),
    url(r'^ajax/get_departament_for_pc_list/(?P<pk>\d+)/$',         vc.GetDepartamentForPcListView.as_view()),
    url(r'^ajax/get_profile_src_img/(?P<pk>\d+)/$',                 vp.GetProfileImgView.as_view()),
    url(r'^ajax/get_company_for_add_dep/$',                         vc.GetCompanyForAddDepartametView.as_view()),
    url(r'^ajax/get_dep_list_for_dep_list/(?P<pk>\d+)/$',           vc.GetDepartamentsForDeplistView.as_view()),
    url(r'^ajax/get_dep_list_for_add_pc/(?P<pk>\d+)/$',             vc.GetDepartamentsForAddPCView.as_view()),
    url(r'^ajax/get_posts_for_add_ques/(?P<pk>\d+)/$',              vc.GetPostsForQuestionAddView.as_view()),
    url(r'^ajax/get_user_from_for_ques/(?P<pk>\d+)/$',              vc.GetPcFromForAddQues.as_view(), name='ajax_GetPcFromForAddQues'),
    url(r'^ajax/change_status_ques/(?P<pk>\d+)/(?P<user_check>\w+)/$', views.QuesChangeStatus.as_view()),
    url(r'^ajax/get_accounting_debts/$',                            vb.GetDebtsView.as_view()),
    url(r'^ajax/get_company_for_accounting/$',                      vb.GetCompanyForAccountingView.as_view()),
    url(r'^ajax/get_debs_for_one_company/(?P<pk>\d+)/$',            vb.GetDebsForOneCompanyView.as_view()),
    url(r'^ajax/get_contracts/(?P<pk>\d+)/$',                       vb.GetContractsView.as_view()),
    url(r'^ajax/change_accounting_status/(?P<pk>\d+)/(?P<status>\w+)/$', vb.EditAccountingView.as_view()),


)


if not settings.HOSTER:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),


        #tests
        url('^test/$', vc.test.as_view(), name='test'),
    )

project/ques/models.py
# -*- coding:utf-8 -*-
from django.db import models

from company import models as com
from django.contrib.contenttypes import generic
from files.models import Files


class Questions(models.Model):
    """
    Модель вопросов пользоватлей
    user_from - от кого вопрос если отправлет администратор
    pc_from - от компьютера в фирме
    user_to - кому адресован вопрос из админов
    date - дата создания
    body - тело вопроса
    user_check - пометка от пользователя что вопрос закрыт
    user_check_date - дата закрытия вопроса
    admin_check - пометка от администратора что вопрос закрыт
    admin_check_date - дата закртия вопроса
    """
    user_from        = models.ForeignKey(com.User, verbose_name=u'От кого', related_name=u'rel_user_from')
    pc_from          = models.ForeignKey(com.CompanyPC, verbose_name=u'От пользователя', related_name=u'rel_px_from', blank=True, null=True)
    worker_from      = models.TextField(u'ФИО', blank=True)
    user_to          = models.ForeignKey(com.User, verbose_name=u'Кому', related_name=u'rel_user_to')
    date             = models.DateTimeField(u'Дата создания')
    body             = models.TextField(u'Вопрос')
    user_check       = models.BooleanField(u'Отметка пользователя')
    user_check_date  = models.DateTimeField(u'Дата закрытия вопроса отправителем', null=True, blank=True)
    slug             = models.CharField(u'Идентификатор', unique=True, null=True, blank=True, max_length=8 )
    answers          = models.PositiveIntegerField(u'Число ответов', default=0)
    post             = models.ForeignKey(com.Posts, verbose_name=u'Тематика вопроса', blank=True, null=True, related_name='rel_quest_posts')
    department       = models.ForeignKey(com.Departments, verbose_name=u'Отдел', null=True, blank=True, related_name='rel_question_deps')


    def __unicode__(self):
        return u'%s : %s' % (self.slug, self.user_to)

    @models.permalink
    def get_absolute_url(self):
        return ('chat', [str(self.id)])

    class Meta:
        ordering = ['-date']
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'



class Chat(models.Model):
    """
    Модель чата к определенному вопросу
    question - вопрос к которому идет чат
    admin_name - если сообщение отправляет администратор то его аккаунт
    date - дата создания сообщения
    body - тело сообщения
    """
    question   = models.ForeignKey(Questions, verbose_name=u'Вопрос', related_name=u'rel_question_chat')
    admin_name = models.ForeignKey(com.User, verbose_name=u'Отправитель', related_name=u'rel_admin_name', blank=True, null=True)
    date       = models.DateTimeField(u'Дата создания')
    body       = models.TextField(u'Сообщение')
    files      = generic.GenericRelation(Files)

    def __unicode__(self):
        return u'%s' % (self.date, )


    class Meta:
        ordering = ['-date']
        verbose_name = u'Сообщение чата'
        verbose_name_plural = u'Сообщения чата'


class Emails(models.Model):
    """
    Модель для отправки почтовых сообщений
    """
    mail_to = models.EmailField()
    subject = models.CharField(max_length=60)
    body    = models.TextField()
    sended  = models.BooleanField()

    def __unicode__(self):
        return self.subject

project/buh/forms.py
# -*- coding:utf-8 -*-
__author__ = 'michael'
from django import forms
from company.models import Company
from buh.models import Contracts, Accounting
from datetime import datetime
from proj.utils.formUtils import ExtFormMixin

MONTH_CHOISE = (
    ('1','январь'),
    ('2', 'февраль'),
    ('3' , 'март'),
    ('4' , 'апрель'),
    ('5' , 'май'),
    ('6' , 'июнь'),
    ('7' , 'июль'),
    ('8' , 'август'),
    ('9' , 'сентябрь'),
    ('10' , 'октябрь'),
    ('11' , 'ноябрь'),
    ('12' , 'декабрь'),
)

class AddAccountingForm(ExtFormMixin, forms.Form):
    """
    Форма для добавления отчетности
    """

    company  = forms.ModelChoiceField(queryset=Company.objects.all(), label=u'Компания')
    contract = forms.ModelChoiceField(queryset=Contracts.objects.all()[:1], label=u'Договор')
    month    = forms.ChoiceField(choices=MONTH_CHOISE, label=u'Месяц')
    year     = forms.IntegerField(label='Год', min_value=1990, max_value=2100, initial=datetime.now().year)
    paid     = forms.BooleanField(label=u'Статус', required=False, widget=forms.CheckboxInput(attrs={'title':'Статус оплаты за месяц, если стоит галочка значит компания заплатила.'}))


    def clean(self):
        cleaned_data = super(AddAccountingForm, self).clean()
        contract = cleaned_data['contract']
        month    = cleaned_data['month']
        year     = cleaned_data['year']
        try:
            Accounting.objects.get(contract=contract, month=month, year=year)
            mess = u'Такая отчетность уже существует, измените ее в списке отчетностей'
            raise forms.ValidationError(mess)
        except Accounting.DoesNotExist:
            return cleaned_data



class AddContractForm(ExtFormMixin, forms.ModelForm):
    """
    Форма добавления контракта
    """
    class Meta:
        model = Contracts

project/proj/templates/add_departament.html
{% extends 'main.html' %}

{% block title %}
    Добавить отдел
{% endblock %}

{% block content %}
    <h1>Добавление отдела в компании</h1>
    <div id='question' class='borderLine'>
        <form action="{% url add_dep %}" method="POST">{% csrf_token %}
            <table id='tableForm'>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Добавить" />
        </form>
    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
    function GetCompany()
    {
        var loading =  $('#loading');
        var select = $('#id_company');
        loading.fadeIn();
        select.fadeOut();
        $.ajax({
            url: '/ajax/get_company_for_add_dep/',
            type: 'GET',
            dataType: 'json',
            success: function(jsonData){
                select.empty();
                var option0 = '<option selected="selected" value="">---------</option>';
                select.append(option0);
                var counter = CountObjectProperty(jsonData);
                if(counter != 0){
                    $.each(jsonData, function(id, value){
                        select.append(GetSelectHtml(value));
                    });
                }else{
                    var text = 'Вы не обслуживаете ни одну компанию';
                    AddMessageError(text);
                }
                select.fadeIn();
                loading.fadeOut();
            }
        })
    }
    function GetSelectHtml(value)
    {
        var id = value["id"];
        var name = value["name"];
        return '<option value="'+id+'">'+name+'</option>';
    }
    $(document).ready(function(){
        GetCompany();
    });
    </script>
{% endblock %}

project/proj/templates/add_file_to_pc.html
{% extends 'main.html' %}

{% block title %}
    Добавить файл
{% endblock %}

{% block content %}
    <h1>Добавить файл к ПК</h1>
    <div id='question' class='borderLine'>
        <form enctype="multipart/form-data" method="POST" action="{% url file_for_pc pc_pk%}">{% csrf_token %}
            <table id='tableForm'>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Отправить">
        </form>
    </div>
{% endblock %}

{% block script %}

{% endblock %}

project/proj/templates/add_q.html
{% extends 'main.html' %}

{% block title %}
    Задать вопрос
{% endblock %}


{% block content %}
    <h2>Задать вопрос</h2>
    <div class='container-fluid'>
        <div class="row-fluid">
        </div>
        <div class='row-fluid'>
            <div class='span10 well white-well'>
                <div class="row-fluid">
                    <div class='span12'>
                        <div id="face_wrop">
                            <p>Фотография получателя</p>
                            <div id="admin_face">
                                <img src="{{ MEDIA_URL }}img/fregat_logo.png" width="70" height="70">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class='span12'>
                        <form action="" method="POST" class="form-horizontal" name="{{ form.get_name }}">{% csrf_token %}
                            {% include 'form_template.html' with form=form %}
                            <div class="control-group">
                                <div class="controls">
                                    <button type="submit" class='btn btn-primary btn-large'>Создать вопрос</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class='span2'></div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
    var start = false;
    function OnchangeUserTo()
    {
        $('#id_user_to').change(function(){
            GetPostForUserTo();
        });
    }
    function GetPostForUserTo()
    {
        var select_post = $('#id_post');
        var loading = $('#loading');
        var value_user_to = $('#id_user_to').val();
        loading.fadeIn();
        select_post.fadeOut();
        select_post.empty();
        select_post.removeAttr('disabled');
        select_post.append('<option value="" selected="selected">---------</option>');
        if(value_user_to)
        {
            $.ajax({
                url : '/ajax/get_posts_for_add_ques/'+value_user_to+'/',
                type: 'GET',
                dataType: 'json',
                success: function(data){
                    var counter = CountObjectProperty(data);
                    if(counter != 0){
                        $.each(data, function(id, value){
                            select_post.append('<option value="'+id+'" >'+value+'</option>');
                        });
                    }else{
                        var text = 'Для данного полльзователя нет должностей.';
                        AddMessageError(text);
                    }
                    if(! start)
                    {
                        var getPost = getUrlVars()['post'];
                        if(getPost)
                        {
                            select_post.val(getPost);
                        }
                        start = true;

                    }
                    select_post.fadeIn();
                    loading.fadeOut();
                }
            });
        }else{
            select_post.attr('disabled',"disabled");
            select_post.fadeIn();
            loading.fadeOut();
        }
    }
    function CheckNullPcFrom()
    {
        var select_user_from = $('#id_user_from');
        var loading = $('#loading');
        var options_len = $('option', select_user_from).length;
        loading.fadeIn();
        if( options_len < 2){
            var text = 'У вас нет зарегистрированных компьютеров.';
            AddMessageError(text);
        }
        loading.fadeOut();
    }
    function GetUserToFromGET()
    {
        var userToGet = getUrlVars()['user'];
        if(userToGet)
        {
            $("#id_user_to").val(userToGet);
        }
    }
    function GetUserToImg()
    {
        $('#id_user_to').change(function(){
            $('#admin_face').css('background', 'url() transparent');
            $('#admin_face img').fadeOut();
            var id = $(this).val();
            if(id!=0){
                $.ajax({
                    url: '/ajax/get_profile_src_img/'+id+'/',
                    type: 'GET',
                    dataType: 'json',
                    success: function(data){
                        if(data.img_src)
                        {
                            $('#admin_face img').attr('src', data.img_src);
                        }else{
                            $('#admin_face img').attr('src', "{{ MEDIA_URL }}img/fregat_logo.png");
                        }
                        $('#admin_face img').fadeIn();
                    }
                });
            }
        });
    }
    function GetUserToImgStart()
    {
        $('#admin_face img').fadeOut();
        var id = $('#id_user_to').val();
        if(id!=0)
        {
            $.ajax({
                        url: '/ajax/get_profile_src_img/'+id+'/',
                        type: 'GET',
                        dataType: 'json',
                        success: function(data){
                            if(data.img_src)
                            {
                                $('#admin_face').css('background', '');
                                $('#admin_face img').attr('src', data.img_src);
                            }else{
                                $('#admin_face img').attr('src', "{{ MEDIA_URL }}img/fregat_logo.png");
                            }
                            $('#admin_face img').fadeIn();
                        }
                    });
        }
    }
    function GetPcFrom()
    {
        var loading = $('#loading');
        var department = $('#id_department').val();
        var pcFrom = $('#id_user_from');
        loading.fadeIn();
        pcFrom.fadeOut();
        pcFrom.empty();
        pcFrom.append('<option selected="selected" value="">---------</option>');
        if(department){
            pcFrom.removeAttr('disabled');
            $.ajax({
                url : '/ajax/get_user_from_for_ques/'+department+'/',
                type: 'GET',
                dataType: 'json',
                success: function(data){
                    var counter = CountObjectProperty(data);
                    if(counter != 0){
                        $.each(data, function(id, value){
                            pcFrom.append('<option value="'+id+'">'+value+'</option>');
                        });
                    }else{
                        var text = 'В данном отделе нет комьютеров.';
                        AddMessageError(text);
                        pcFrom.attr('disabled', 'disabled');
                    }
                    pcFrom.fadeIn();
                    loading.fadeOut();
                }
            });
        }else{
            pcFrom.attr('disabled', 'disabled');
            pcFrom.fadeIn();
            loading.fadeOut();
        }
    }
    function OnChangeDep()
    {
        $('#id_department').on('change', function(){
            GetPcFrom();
        });
    }
    $(document).ready(function(){
        GetUserToImg();
        OnchangeUserTo();
        GetUserToFromGET();
        GetUserToImgStart();
        GetPostForUserTo();
        CheckNullPcFrom();
        GetPcFrom();
        OnChangeDep();
    });
    </script>
{% endblock %}

project/proj/templates/add_user.html
{% extends 'main.html' %}

{% block title %}
    Добавить нового пользователя
{% endblock %}

{% block content %}
    <h1>Добавление нового сотрудника</h1>
        <div id='question' class='borderLine'>
            <form action="{% url add_user %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <table id='tableForm' class='user_add'>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Создать" />
            </form>
        </div>
{% endblock %}

{% block script %}

{% endblock %}

project/proj/templates/ajax_get_company_for_report_ques.html
<option selected="selected" value="0">---------</option>
{% for item in companys %}
    <option value="{{ item.com_user.id }}">{{ item.com_user.first_name }}</option>
{% endfor %}

project/proj/templates/ajax_get_users_for_report_for_ques.html
<option selected="selected" value="0">---------</option>
{% for item in users %}
    <option value="{{ item.id }}">{{ item.first_name }} {{ item.last_name }}</option>
{% endfor %}

project/proj/templates/ajax_pc_from.html
<option selected="selected" value="">---------</option>
{% for item in pc %}
<option value="{{ item.id }}">{{ item }}</option>
{% endfor %}

project/proj/templates/edit_article.html
{% extends 'main.html' %}

{% block script %}

{% endblock %}

{% block title %}
    Изменить страницу документации
{% endblock %}


{% block content %}
    <h1>Изменение страницы</h1>
    <div id="add_page">
        <form method="POST" action="">{% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Изменить">
        </form>
    </div>
{% endblock %}

{% block head_script %}
    {{ form.media }}
    <script type="text/javascript">

    </script>
{% endblock %}

project/proj/templates/edit_post.html
{%  extends 'main.html' %}

{% block title %}
    Изменение должности
{% endblock %}

{% block script %}

{% endblock %}

{% block content %}
    <h1>Изменение должности</h1>
    <div id='question' class='borderLine'>
        <form action="" method="POST">{% csrf_token %}
            <table id='tableForm'>
                {{ form.as_table }}
            </table>
            <button type="submit">Изменить</button>
        </form>
    </div>
{% endblock %}

project/proj/templates/form_template.html
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form %}
        <div class="control-group
        {% if field.errors %}
            error
        {% endif %}
        ">
            <label class="control-label" for="id_{{ field.name }}">{{ field.label }}:</label>
            <div class="controls">
                {{ field }}
                {% if field.errors %}
                    <span class="help-inline">
                        {% for error in field.errors %}
                            <strong>{{ error|escape }}</strong><br>
                        {% endfor %}
                    </span>
                {% endif %}
            </div>
        </div>
    {% endfor %}

project/proj/templates/get_history_to_pc_options.html
{% extends 'main.html' %}

{% block title %}
    История изменений характеристик
{% endblock %}

{% block content %}
    <h1>История изменений характеристик комьютера</h1>
    <div id="pc_detail_parent">
        <table>
            <tbody id="table_pc_parent">
            <tr>
                <th>Фирма</th>
                <td>{{ pc.company }}</td>
            </tr>
            <tr>
                <th>ID</th>
                <td>{{ pc.pc_nameId }}</td>
            </tr>
            <tr>
                <th>HOSTNAME</th>
                <td>{{ pc.pc_name }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div id='tableDiv'>
        <div id="preTableTop">
            <p>Количество Изменений {{ paginator.count }}</p>
        </div>
        <table class='listTable'>
            <thead>
            <tr>
                <th>Характеристика</th>
                <th>Значение</th>
                <th>Когда последний раз изменялась</th>
                <th>Кто последний раз изменил</th>
            </tr>
            </thead>
            <tbody id="mainTable">
            {% for opt in options %}
                <tr class='{% cycle 'firstTd' 'secondTd' %}' id="{{ opt.id }}">
                    <td class='valueCol'>{{ opt.option }}</td>
                    <td class='valueCol'>{{ opt.body }}</td>
                    <td class='dateCol' >{{ opt.date }}</td>
                    <td class='dateCol' >{{ opt.user.first_name }} {{ opt.user.last_name }}</td>
                    {% empty %}
                <tr>
                    <td colspan="4">У данного комьютера нет истории характеристик</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <p id='paginator'>&nbsp;
            {% if paginator.num_pages > 1 %}
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">&larr; Предыдущая &nbsp;</a>
                {% endif %}
                <span class="current_page">Страница {{ page_obj.number }} из {{ paginator.num_pages }}.</span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">&nbsp; Следующая &rarr;</a>
                {% endif %}
            {% endif %}
        </p>
    </div>
{% endblock %}

{% block script %}

{% endblock %}